HIA/Controllers/QuestionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using HIA.Models;

namespace HIA.Controllers
{
    public class QuestionsController : Controller
    {
        private HIADBEntities db = new HIADBEntities();
        private PorterStemmer porterstemmer = new PorterStemmer();
        private RemoveStopWords stopWords = new RemoveStopWords();

        // GET: Questions
        public ActionResult Index()
        {
            var question = db.Question.Include(q => q.Language);
            return View(question.ToList());
        } 
        
        public ActionResult EnglishQuestions()
        {
            var question = db.Question.Include(q => q.Language);
            var englishQuestion = question.Where(q => q.lang_id == 1).ToList();

            return View(englishQuestion);
        }
        public ActionResult ArabicQuestions()
        {
            var question = db.Question.Include(q => q.Language);
            var arabicQuestion = question.Where(q => q.lang_id == 2).ToList();

            return View(arabicQuestion);
        }

        public ActionResult ChooseLanguage(int id)
        {
            if (id == 1)
            {
                ViewBag.language = 1;
            }
            else
            {
                ViewBag.language = 2;
            }

            return View();
        }

        // GET: Questions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Question question = db.Question.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            return View(question);
        }

        // GET: Questions/Create
        public ActionResult Create()
        {
            ViewBag.lang_id = new SelectList(db.Language, "id", "lang_name");
            return View();
        }

        // POST: Questions/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,question1,answer,lang_id")] Question question)
        {
   
            if (ModelState.IsValid)
            {
                int numberOfQuestion                     = db.Question.Count();
                int numberOfQuestionContainsKey          = 0;
                string SearchText                        = question.question1 + " " + question.answer;
                string SearchQuery                       = SearchText.ToLower();
                List<string> questionToList              = testQuestion(SearchQuery);
                Dictionary<string, int>  Indexes         = new Dictionary<string, int>();
        

                    // Add Question to Questions Table
                    db.Question.Add(question);
                    db.SaveChanges();

                    foreach (var item in questionToList)
                    {
                        if (Indexes.ContainsKey(item))
                        {
                            Indexes[item] = Indexes[item] + 1;
                        }
                        else
                        {
                            Indexes.Add(item, 1);
                        }
                    }

                    foreach (var item in Indexes)
                    {
                        if(question.lang_id == 1)
                        {
                            EnglishIndex index = new EnglishIndex()
                            {
                                term = item.Key,
                                question_id = question.id,
                                tf = (double)item.Value / (double)Indexes.Keys.Count()
                            };

                            numberOfQuestionContainsKey = db.EnglishIndex.Where(j => j.term == item.Key && j.question_id != question.id).Distinct().Count() + 1;
                            index.idf = Math.Log10(numberOfQuestion / numberOfQuestionContainsKey);
                            if (index.idf < 0)
                                index.idf = 0;
                            index.weight = index.tf * index.idf;
                            db.EnglishIndex.Add(index);
                            db.SaveChanges();
                        }

                        else
                        {
                            ArabicIndex index = new ArabicIndex()
                            {
                                term        = item.Key,
                                question_id = question.id,
                                tf          = (double)item.Value / (double)Indexes.Keys.Count()
                            };

                            numberOfQuestionContainsKey = db.ArabicIndex.Where(j => j.term == item.Key && j.question_id != question.id).Distinct().Count() + 1;
                            index.idf                       = Math.Log10(numberOfQuestion / numberOfQuestionContainsKey);
                            if (index.idf < 0)
                                index.idf = 0;
                            index.weight                    = index.tf * index.idf;
                            db.ArabicIndex.Add(index);
                            db.SaveChanges();
                        }

                    }

            }

            ViewBag.lang_id = new SelectList(db.Language, "id", "lang_name", question.lang_id);

            return RedirectToAction("Index");
        }

        // GET: Questions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Question question = db.Question.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            ViewBag.lang_id = new SelectList(db.Language, "id", "lang_name", question.lang_id);
            return View(question);
        }

        // POST: Questions/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,question1,answer,lang_id")] Question question)
        {
            if (ModelState.IsValid)
            {
                db.Entry(question).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.lang_id = new SelectList(db.Language, "id", "lang_name", question.lang_id);
            return View(question);
        }

        // GET: Questions/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Question question = db.Question.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            return View(question);
        }

        // POST: Questions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Question question = db.Question.Find(id);
            db.Question.Remove(question);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public List<string> testQuestion(string text)
        {
            bool detectLanguage = stopWords.HasArabicCharacters(text);

            List<string> listOfWord;

            if (detectLanguage == true)
            {
                // Arabic stop word -- return text without stop words
                string removeArabicStopWord = stopWords.StopWordsStrip(text);

                // Arabic stemmer --- return all words to root
                string arabicStemming = stopWords.ArabicStemming(removeArabicStopWord);

                // make all words as list without empty.
                listOfWord = porterstemmer.stringToList(arabicStemming);

            }

            else
            {
                // English stop word -- return text without stop words
                string removeEnglishStopWord = porterstemmer.englishStopWordsStrip(text);

                // Englisgh stemmer --- return all words to root
                string englishStemmerText = porterstemmer.englishWordsStrip(removeEnglishStopWord);

                // make all words as list without empty.
                listOfWord = porterstemmer.stringToList(englishStemmerText);
                
            }


            return listOfWord;

        }

    }
}

HIA/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

HIA/Views/Home/BooleanModel.cshtml
@model IEnumerable<HIA.Models.Question>

@{
    ViewBag.Title = "Index";
}


@Html.ActionLink(" Back","Index","Home",null,new { @class = "glyphicon glyphicon-arrow-left btn btn-primary" })

<h2>@ViewBag.resultLabel <b style="color:red;">@ViewData["TXT"]</b></h2>

<br />

@foreach (var item in Model)
{
    <div class="list-group">
        <a  class="list-group-item" href="@Url.Action("Details","Questions",new { id= item.id})">
            <div class="list-group-item-heading">
                <h3 class="media-heading">
                    @Html.Raw(@item.question1.Replace((string)ViewData["TXT"], "<span style='background-color:lightblue;'>" + (string)ViewData["TXT"] + "</span>"))
                </h3>
                <hr />
                <h4>
                     @Html.Raw(@item.answer.Replace((string)ViewData["TXT"], "<span style='background-color:yellow;'>" + (string)ViewData["TXT"] + "</span>"))
                 </h4>
            </div>
        </a>
    </div>

}

HIA/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

HIA/Views/Home/ExtendedBooleanModel.cshtml
@model IEnumerable<HIA.Models.Question>

@{
    ViewBag.Title = "Index";
}

@Html.ActionLink(" Back", "Index", "Home", null, new { @class = "glyphicon glyphicon-arrow-left btn btn-primary" })

<h2>@ViewBag.resultLabel <b style="color:red;">@ViewData["TXT"]</b></h2>

<br />

@foreach (var item in Model)
{
    <div class="list-group">
        <a class="list-group-item" href="@Url.Action("Details","Questions",new { id= item.id})">
            <div class="list-group-item-heading">
                <h3 class="media-heading">
                    @Html.Raw(@item.question1.Replace((string)ViewData["TXT"], "<span style='background-color:lightblue;'>" + (string)ViewData["TXT"] + "</span>"))
                </h3>
                <hr />
                <h4>
                    @Html.Raw(@item.answer.Replace((string)ViewData["TXT"], "<span style='background-color:yellow;'>" + (string)ViewData["TXT"] + "</span>"))
                </h4>
            </div>
        </a>
    </div>

}

HIA/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<style>
    input, select, textarea {
        max-width: 900px;
    }

    .btn-lg, .btn-group-lg > .btn {
        padding: 10px 45px;
        font-size: 18px;
        line-height: 1.3333333;
        border-radius: 10px;
    }

    .input-group {
        position: relative;
        display: table;
        border-collapse: separate;
        height: 50px;
    }

        .input-group .form-control {
            position: relative;
            z-index: 2;
            float: left;
            width: 100%;
            margin-bottom: 0;
            height: 50px;
        }

    body {
        padding-top: 17px;
        padding-bottom: 20px;
        background-color:antiquewhite    }
</style>

<script src="~/Scripts/jquery-3.4.1.js"></script>

<script type="text/javascript">
    $(document).ready(function () {

        $('#imgBool').click(function () {
            var href = $(this).find("a").attr("href");
            if (href) {
                window.location = href;
            }
            var textValue = $('#txtValue').val();
            alert(textValue);

        });

        $('#imgBool').hover(function () {
            $(this).css('cursor', 'pointer');
        });
    });
</script>


        <div class="jumbotron" style="padding-top:1%;">
            <div>
                <img alt="logo" src="~/Content/Images/logo1.png" style="padding-left:40%;" />
            </div>

            <label for="basic-url">Ask for any advice</label>
            <div class="input-group">
                <span class="input-group-addon" id="basic-addon3">Type your word</span>
                <input id="txtValue" type="text" class="form-control" placeholder="Enter your Question..." style="width:100%">
            </div>

        </div>

        <div class="row">
            <div class="row">
                @Html.AntiForgeryToken()

                <div id="booleanDiv" class="col-sm-6 col-md-4">
                    <div class="thumbnail">
                        <img id="imgBool" src="~/Content/Images/ee.png" />
                        <div class="caption">
                            <h3>Boolean Model</h3>
                            @Html.ActionLink("Search", "BooleanModel", "Home", new AjaxOptions { HttpMethod = "POST" }, new { @id = "btnBoolean", @class = "btn-pill btn-shadow btn-wide fsize-1 btn btn-success btn-lg", onclick = "BooleanModel(this)" })
                        </div>
                    </div>
                </div>

                <div class="col-sm-6 col-md-4">
                    <div class="thumbnail">
                        <img src="~/Content/Images/bb.png" />
                        <div class="caption">
                            <h3>Extended Boolean Model</h3>
                            @Html.ActionLink("Search", "ExtendedBooleanModel", "Home", new AjaxOptions { HttpMethod = "POST" }, new { @id = "btnExtendedBoolean", @class = "btn-pill btn-shadow btn-wide fsize-1 btn btn-primary btn-lg", onclick = "ExtendedBooleanModel(this)" })
                        </div>
                    </div>
                </div>

                <div class="col-sm-6 col-md-4">
                    <div class="thumbnail">
                        <img src="~/Content/Images/vv.jpg" />
                        <div class="caption">
                            <h3>Vector Model</h3>
                            @Html.ActionLink("Search", "VectorModel", "Home", new AjaxOptions { HttpMethod = "POST" }, new { @id = "btnVector", @class = "btn-pill btn-shadow btn-wide fsize-1 btn btn-warning btn-lg", onclick = "VectorModel(this)" })
                        </div>
                    </div>
                </div>

            </div>
        </div>



<script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
<script src="~/Scripts/jquery-3.4.1.js"></script>

<script type="text/javascript">
    function BooleanModel(e) {

        var text = $("#txtValue").val();

        var url = e.href = "/Home/BooleanModel?searchText=" + text;
        $.ajax(url).then(function (data) {
            type: "GET"
        });
    }
    function ExtendedBooleanModel(e) {

        var text = $("#txtValue").val();

        var url = e.href = "/Home/ExtendedBooleanModel?searchText=" + text;
        $.ajax(url).then(function (data) {
            type: "GET"
        });
    }
    function VectorModel(e) {

        var text = $("#txtValue").val();

        var url = e.href = "/Home/VectorModel?searchText=" + text;
        $.ajax(url).then(function (data) {
            type: "GET"
        });
    }
</script>

HIA/Views/Home/VectorModel.cshtml
@model IEnumerable<HIA.Models.Question>

@{
    ViewBag.Title = "Index";
}

@Html.ActionLink(" Back", "Index", "Home", null, new { @class = "glyphicon glyphicon-arrow-left btn btn-primary" })

<h2>@ViewBag.resultLabel <b style="color:red;">@ViewData["TXT"]</b></h2>

<br />

@foreach (var item in Model)
{
    <div class="list-group">
        <a class="list-group-item" href="@Url.Action("Details","Questions",new { id= item.id})">
            <div class="list-group-item-heading">
                <h3 class="media-heading">
                    @Html.Raw(@item.question1.Replace((string)ViewData["TXT"], "<span style='background-color:lightblue;'>" + (string)ViewData["TXT"] + "</span>"))
                </h3>
                <hr />
                <h4>
                    @Html.Raw(@item.answer.Replace((string)ViewData["TXT"], "<span style='background-color:yellow;'>" + (string)ViewData["TXT"] + "</span>"))
                </h4>
            </div>
        </a>
    </div>

}